camel.main.name = capability-sidecar
engine.rest = http://cibseven:8080/engine-rest
worker.id   = camel-sidecar

externaltask.maxTasks     = 5
externaltask.lockDuration = 30000
outbound.pollMs           = 2000

camel.component.kafka.brokers = kafka:9092
